---
title: "Atacama soils: demo analyses"
author: "daniel.lundin@lnu.se"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output:
  html_document: 
    toc: yes
  pdf_document:
    fig_caption: yes
    fig_height: 9
    fig_width: 8
    number_sections: yes
    toc: yes
---

# Setup

## Options

```{r setup, echo=F, cache = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = 'figures/', cache = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
```

## Libraries

```{r libraries, message=F, cache = FALSE}
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(kfigr))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(edgeR))
suppressPackageStartupMessages(library(vegan))
```

## Constants

```{r constants}
MIN_LIB_SIZE = 2000

LOW_ELEVATION = 1500
MID_ELEVATION = 3000
```

# Read data files

```{r read-data}
counts <- read_tsv('atacama-soils.asvtable.tsv', col_types = cols(.default = col_integer(), seqid = col_character())) %>%
  gather(sample, count, 2:ncol(.)) %>%
  filter(count > 0) %>%
  group_by(sample) %>% mutate(relab = count/sum(count)) %>% ungroup()

samples <- read_tsv(
  'atacama-soils.samples.header.tsv',
  col_types = cols(
    .default = col_double(),
    SampleID = col_character(), BarcodeSequence = col_character(), LinkerPrimerSequence = col_character(),
    Elevation = col_integer(), ExtractGroupNo = col_character(), TransectName = col_character(),
    SiteName = col_character(), Depth = col_integer(), TOC = col_integer(), Vegetation = col_character(),
    Description = col_character()
  )
) %>%
  rename(sample = SampleID) %>%
  group_by(SiteName, Depth) %>% mutate(repl = rank(sample)) %>% ungroup()

taxonomy <- read_tsv(
  'atacama-soils.taxonomy.tsv',
  col_types = cols(.default = col_character(), Confidence = col_double())
) %>%
  mutate(thier = gsub('D_[0-9]+__', '', Taxon)) %>% select(-Taxon) %>%
  separate(thier, c('domain', 'phylum', 'class', 'order', 'family', 'genus', 'species'), sep = ';', fill = 'right') %>%
  rename(seqid = `Feature ID`)
```

## Sample summary

```{r sample-summary}
samples %>% select(4, 10:14, 18, 22) %>% summary()
```

## Sequencing depth

```{r seqdepth, fig.height = 7}
counts %>% group_by(sample) %>% summarise(count = sum(count)) %>% ungroup() %>%
  ggplot(aes(x = sample, y = count)) +
  geom_point() +
  geom_hline(yintercept = MIN_LIB_SIZE, linetype = 'dashed') +
  coord_flip()
```

## Delete too small libraries

```{r min-lib-size}
counts <- counts %>% group_by(sample) %>% mutate(sum_count = sum(count)) %>% ungroup() %>%
  filter(sum_count > MIN_LIB_SIZE) %>% select(-sum_count)
```

## Calculate 10 most abundant phyla

```{r top10phyla}
top10phyla <- counts %>% inner_join(taxonomy, by = 'seqid') %>%
  group_by(phylum, sample) %>%
  summarise(relab = sum(relab)) %>%
  summarise(mean_relab = mean(relab)) %>%
  ungroup() %>%
  top_n(10, mean_relab)
```

# Phylum bar plot

```{r phylum-bars, fig.height = 8}
counts %>% inner_join(samples, by = 'sample') %>%
  inner_join(taxonomy, by = 'seqid') %>%
  left_join(top10phyla %>% transmute(phylum, topphylum = phylum), by = 'phylum') %>%
  replace_na(list('topphylum' = 'Other phyla')) %>%
  group_by(SiteName, Depth, topphylum, repl) %>% 
  summarise(relab = sum(relab)) %>% 
  summarise(relab = mean(relab)) %>% 
  ungroup() %>%
  ggplot(aes(x = SiteName, y = relab, fill = topphylum)) +
  geom_col() +
  scale_fill_brewer(palette = 'Paired') +
  facet_wrap(~Depth, ncol = 1) +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
  )
```

# Calculating normalised data

```{r edger-normalise}
edger <- counts %>% select(-relab) %>%
  spread(sample, count, fill = 0) %>%
  data.frame() %>%
  tibble::column_to_rownames('seqid') %>%
  DGEList() %>%
  calcNormFactors(method = 'TMM')

# Add normalised cpms to counts table
counts <- counts %>%
  left_join(
    edger %>% cpm() %>% 
      data.frame() %>% tibble::rownames_to_column('seqid') %>%
      gather(sample, cpm, 2:ncol(.)) %>% filter(cpm > 0),
    by = c('seqid', 'sample')
  )
```

## Barplot of normalised data

```{r phylum-bars-normalised, fig.height = 8, fig.width=8}
counts %>% inner_join(samples, by = 'sample') %>%
  inner_join(taxonomy, by = 'seqid') %>%
  left_join(top10phyla %>% transmute(phylum, topphylum = phylum), by = 'phylum') %>%
  replace_na(list('topphylum' = 'Other phyla')) %>%
  group_by(sample, topphylum, repl) %>% 
  summarise(cpm = sum(cpm)) %>% 
  ungroup() %>%
  ggplot(aes(x = sample, y = cpm, fill = topphylum)) +
  geom_col(position = 'fill') +
  scale_fill_brewer(palette = 'Paired') +
  theme(
    axis.text.x = element_text(angle = 60, hjust = 1)
  )
```

# Diversity indices

## Alpha diversity

```{r alpha-diversity, fig.width = 8, fig.height = 8}
shannon <- counts %>% select(seqid, sample, cpm) %>%
  spread(seqid, cpm, fill = 0) %>%
  data.frame() %>% tibble::column_to_rownames('sample') %>%
  diversity() %>% data.frame(shannon = .) %>% tibble::rownames_to_column('sample')
shannon %>%
  inner_join(samples, by = 'sample') %>%
  ggplot(aes(x = TransectName, y = shannon, colour = AverageSoilRelativeHumidity)) +
  geom_boxplot() + geom_jitter() +
  scale_colour_viridis_c() +
  facet_wrap(~Depth, ncol = 1) +
  theme(
    legend.position = 'bottom'
  )
```

## Beta diversity

```{r nmds, include = FALSE}
nmds <- counts %>% select(seqid, sample, cpm) %>%
  spread(seqid, cpm, fill = 0) %>%
  data.frame() %>% tibble::column_to_rownames('sample') %>%
  metaMDS(k = 3, trymax = 100)
```

```{r plotnmds-func}
plotnmds <- function(colourvar) {
  wrapr::let(
    c(c = colourvar),
    {
      nmds$points %>% broom::tidy() %>% rename(sample = .rownames) %>%
        inner_join(samples, by = 'sample') %>%
        ggplot(aes(x = MDS1, y = MDS2, shape = TransectName, colour = c)) +
        geom_point() +
        geom_text(aes(label = SiteName), nudge_y = 0.1, colour = 'black', size = 2) +
        scale_colour_viridis_c() +
        theme(
          legend.position = 'bottom'
        )
    }
  )
}
```

```{r nmds-humidity-plot, warning = FALSE, fig.height = 6, fig.cap = 'NMDS coloured by relative humidity.'}
plotnmds('AverageSoilRelativeHumidity')
```

```{r nmds-ph-plot, warning = FALSE, fig.height = 6, fig.cap = 'NMDS coloured by pH.'}
plotnmds('pH')
```
```{r nmds-temperature-plot, warning = FALSE, fig.height = 6, fig.cap = 'NMDS coloured by temperature.'}
plotnmds('AverageSoilTemperature')
```

## PERMANOVA

```{r permanova}
c <- counts %>% select(sample, seqid, cpm) %>% spread(seqid, cpm, fill = 0) %>%
  data.frame() %>% tibble::column_to_rownames('sample')
s <- samples %>% filter(sample %in% rownames(c)) %>%
  mutate(
    AverageSoilTemperature = ifelse(
      is.na(AverageSoilTemperature), mean(AverageSoilTemperature, na.rm = TRUE), AverageSoilTemperature
    ),
    AverageSoilRelativeHumidity = ifelse(
      is.na(AverageSoilRelativeHumidity), mean(AverageSoilRelativeHumidity, na.rm = TRUE), AverageSoilRelativeHumidity
    )
  ) %>%
  data.frame() %>% tibble::column_to_rownames('sample')
adonis(c ~ AverageSoilRelativeHumidity * pH * TransectName, data = s)
```

## Correlations in the sample data?

(See also blog post: https://datascienceplus.com/visualizations-for-correlation-matrices-in-r/)

```{r ph-to-humidity, fig.height = 3, warning = FALSE}
samples %>% 
  inner_join(shannon, by = 'sample') %>%
  ggplot(aes(x = AverageSoilRelativeHumidity, y = pH, colour = shannon)) +
  geom_point() +
  scale_colour_viridis_c() +
  geom_smooth(method = 'lm', formula = y ~ x) +
  facet_wrap(~TransectName, ncol = 2) +
  theme(
    legend.position = 'bottom'
  )
```

