download:
	wget https://data.qiime2.org/2018.8/tutorials/atacama-soils/sample_metadata.tsv
	wget https://data.qiime2.org/2018.8/tutorials/atacama-soils/10p/forward.fastq.gz https://data.qiime2.org/2018.8/tutorials/atacama-soils/10p/reverse.fastq.gz https://data.qiime2.org/2018.8/tutorials/atacama-soils/10p/barcodes.fastq.gz
